# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  prefix: "/api/v1"

# GCP Settings
gcp:
  project_id: ""  # Set via env var GCP_PROJECT_ID
  bucket_name: ""  # Set via env var GCP_BUCKET_NAME
  region: "us-central1"

# Streamlit Settings
streamlit:
  page_title: "My App"
  page_icon: "🚀"
  layout: "wide"

# Application Settings
app:
  cache_ttl: 3600  # seconds
  max_upload_size: 10485760  # 10MB in bytes
  allowed_extensions: [".pdf", ".txt", ".csv"]
  # Add URLs here if you want to configure them
  # target_urls:
  #   - "https://www.dhs.gov/immigration-statistics/yearbook/2022"
  #   - "https://www.dhs.gov/topics/cybersecurity"

# Vector Database (Vertex AI Matching Engine)
vector_db:
  index_id: ""           # Set via env var VECTOR_DB_INDEX_ID
  index_endpoint_id: "" # Set via env var VECTOR_DB_INDEX_ENDPOINT_ID
  num_neighbors: 10 