# eidbi-query-system/cloudbuild.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA', '-f', 'Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eidbi-backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '25849992695-compute@developer.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,GCP_BUCKET_NAME=eidbi-system-bucket-2024'

# Define images to push to Google Container Registry (GCR) or Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA'

# Optional: Define substitutions
# substitutions:
#   _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY 

