# eidbi-query-system/cloudbuild.yaml

steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend/']
    id: 'build-backend'

  # Push the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eidbi-backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'id-eidbi-service-account@lyrical-ward-454915-e6.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,GCP_BUCKET_NAME=eidbi-system-bucket-lyrical-ward'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eidbi-frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', 'frontend/']
    id: 'build-frontend'

  # Push the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eidbi-frontend:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eidbi-frontend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eidbi-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'id-eidbi-service-account@lyrical-ward-454915-e6.iam.gserviceaccount.com'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# Define images to push to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/eidbi-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/eidbi-frontend:$COMMIT_SHA'

# Optional: Define substitutions
# substitutions:
#   _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY 

